# version: '3.8'
# services:
#   agiiza-dev-db:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5434:5432"
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     networks:
#       - agiizaapi

# networks:
#   agiizaapi:

version: '3.8'
services:
  agiiza-dev-db:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - agiizaapi

networks:
  agiizaapi:
volumes:
  db_data:
